<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_10</name>
   <tag></tag>
   <elementGuidId>b7d4c385-b67e-4c6a-b95d-7e4ce1d521c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-datepicker-div']/table/tbody/tr[2]/td[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ui-state-default.ui-state-highlight.ui-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87197a0b-6c7d-416c-adad-7cb036bb4f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-state-default ui-state-highlight ui-state-hover</value>
      <webElementGuid>6dedee8e-322d-46bc-ba25-9f7371d001c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>88b5282a-8b23-4720-8d29-6d9ec71753b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0f8f1e6d-0b51-4b54-979a-99ce21612428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>95e74b13-010e-4446-a5db-7dc8b123fcc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>58683e86-3a0e-4759-836e-39b0bd35d8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-datepicker-div&quot;)/table[@class=&quot;ui-datepicker-calendar&quot;]/tbody[1]/tr[2]/td[@class=&quot;ui-datepicker-days-cell-over  ui-datepicker-today&quot;]/a[@class=&quot;ui-state-default ui-state-highlight ui-state-hover&quot;]</value>
      <webElementGuid>c7126948-1a3c-4ad6-9b0f-eb1d891cb74e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-datepicker-div']/table/tbody/tr[2]/td[5]/a</value>
      <webElementGuid>d463115a-e060-4d3d-a523-7fc148325fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'10')]</value>
      <webElementGuid>b7a95d2c-e81e-4a40-a37d-f456af2e60e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::a[10]</value>
      <webElementGuid>adc0b025-dd64-427c-b629-849c4260bead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::a[10]</value>
      <webElementGuid>a4820e39-83da-4a74-a30d-198c23a92751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>efadcfba-8f16-4f25-aded-935cc4f44f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/a</value>
      <webElementGuid>db72ce76-c5f2-4ecd-8b43-784f229e737d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '10' or . = '10')]</value>
      <webElementGuid>aecf9a73-2d6b-401f-b15c-55f3a0eebc78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
