<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Number_vfb-19</name>
   <tag></tag>
   <elementGuidId>3c0163bd-fd5d-43e3-a222-33f5a1e2e4f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-19']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-19</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c56da74-534d-4e5b-a860-0a1fff5b99e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c51e5594-98c4-4a4d-9949-a2c529729357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-19</value>
      <webElementGuid>41a1d62e-11ac-445e-9bf6-ba300d9056ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-19</value>
      <webElementGuid>cfe63f36-6193-4093-ac5b-2aef258701f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium   digits </value>
      <webElementGuid>c040a47f-730b-4e4a-a525-cf33d8bee9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-19&quot;)</value>
      <webElementGuid>0aa34be1-d6e6-46f5-9055-dc5408e0a02e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-19']</value>
      <webElementGuid>ee3c0137-dc09-419c-9600-5d38c588e53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-19']/input</value>
      <webElementGuid>316d5ddb-f8c0-419e-8dd7-5147d287d6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/input</value>
      <webElementGuid>51e95c91-c033-4b6c-b7d5-f13baa48c9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-19' and @id = 'vfb-19']</value>
      <webElementGuid>dbc7a40d-6e6f-47e8-81d5-dd46f2994a32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
